version: '2.2'
services:
  fproxy:
    container_name: fproxy
    image: demanproxy:latest
    volumes:
      - ./config.yml:/usr/fproxy/config.yml
    ports:
      - "8989:8080"
    #restart: always
    environment:
      - INSTANCES=2
      - MON_HTTP_PORT=7777
      - PROXY_HTTP_PORT=8282
      - CONFIG_FILE=/usr/fproxy/config.yml
